// Blog post metadata — the single source of truth for the blog index, the
// per-post <head>, the sitemap, and JSON-LD. The article *bodies* live in
// components/blog/articles/* and are wired to slugs in app/blog/[slug]/page.tsx,
// so this file stays lightweight and importable from the sitemap.

// The bylined author for every article (real name + photo = E-E-A-T).
export const AUTHOR = {
  name: 'Sinh Yang',
  avatar: '/authors/sinh-yang', // .avif + .webp in public/authors
  role: 'Founder of Revova',
  bio: 'Sinh Yang is the founder of Revova. He writes about payment recovery, dunning, and reducing churn for subscription businesses.',
} as const

export type BlogPost = {
  slug: string
  title: string
  description: string
  excerpt: string
  date: string // ISO date, publication
  updated?: string
  author: string
  category: string
  readingMinutes: number
  hero?: string // /public path WITHOUT extension; .avif + .webp are generated by scripts/gen-blog-images.mjs
  heroAlt?: string
}

export const posts: BlogPost[] = [
  {
    slug: 'revova-vs-competitors-2026',
    title: 'Revova vs Churnkey, Churn Buster, Stunning & More (2026 Comparison)',
    description:
      'Revova compared head-to-head with Churnkey, Paddle Retain, Churn Buster, Stunning, Baremetrics Recover and Stripe’s native retries — pricing, features, and which to pick.',
    excerpt:
      'Head-to-head: Revova vs Churnkey, Paddle Retain, Churn Buster, Stunning, Baremetrics Recover and DIY Stripe retries — honest pros, cons, pricing, and who each is for.',
    date: '2026-07-11',
    author: 'Sinh Yang',
    category: 'Comparison',
    readingMinutes: 15,
    hero: '/blog/revova-vs-competitors-2026-hero',
    heroAlt: 'Revova’s $29 price card highlighted next to greyed-out competitor price tags on a dark background',
  },
  {
    slug: 'revova-review-2026',
    title: 'Revova Review (2026): An Honest, In-Depth Look at the Payment-Recovery Tool',
    description:
      'A candid, in-depth Revova review for 2026 — setup, the AI recovery email engine, the Lost Revenue Finder, pricing, pros and cons, and who it is (and isn’t) for.',
    excerpt:
      'A candid, feature-by-feature review of Revova — no-code setup, the AI recovery email sequence, the Lost Revenue Finder, honest pros and cons, pricing, and who it’s for.',
    date: '2026-07-11',
    author: 'Sinh Yang',
    category: 'Review',
    readingMinutes: 14,
    hero: '/blog/revova-review-2026-hero',
    heroAlt: 'A Revova product review scorecard with a 4.5 out of 5 rating badge on a dark, on-brand background',
  },
  {
    slug: 'best-payment-recovery-dunning-tools-2026',
    title: 'The 6 Best Payment Recovery (Dunning) Tools in 2026, Compared',
    description:
      'An honest comparison of the best failed-payment recovery tools in 2026 — Churnkey, Churn Buster, Stunning, Baremetrics Recover, Paddle Retain and Revova — with pricing, pros, cons, and how to choose.',
    excerpt:
      'Churnkey, Churn Buster, Stunning, Baremetrics Recover, Paddle Retain and Revova — what each is good at, roughly what it costs, and which one fits your stage and stack.',
    date: '2026-07-08',
    author: 'Sinh Yang',
    category: 'Comparison',
    readingMinutes: 15,
    hero: '/blog/best-payment-recovery-dunning-tools-2026-hero',
    heroAlt: 'Illustration of subscription revenue bars with failed payments being recovered back up',
  },
  {
    slug: 'how-to-recover-failed-stripe-payments',
    title: 'How to Recover Failed Stripe Payments: A 2026 Step-by-Step Guide',
    description:
      'Recover failed Stripe payments in 2026: smart retries, personalized dunning emails, pre-dunning, SCA handling and recovering past failures — a clear step-by-step guide.',
    excerpt:
      'Smart retries, personalized dunning emails, pre-dunning, SCA handling, and recovering the failures you’ve already lost — the full Stripe recovery stack, step by step.',
    date: '2026-07-08',
    author: 'Sinh Yang',
    category: 'Guide',
    readingMinutes: 11,
    hero: '/blog/how-to-recover-failed-stripe-payments-hero',
    heroAlt: 'A declined credit card recovered via a retry arc into a green checkmark',
  },
  {
    slug: 'what-is-involuntary-churn',
    title: 'What Is Involuntary Churn? (And How to Stop It) — 2026 Guide',
    description:
      'Involuntary churn is revenue lost to failed payments, not cancellations. Learn what it is, how it differs from voluntary churn, what it costs, and how to reduce it.',
    excerpt:
      'The churn caused by failed payments, not cancellations — what it is, how it differs from voluntary churn, why it compounds, and the proven stack to reduce it.',
    date: '2026-07-08',
    author: 'Sinh Yang',
    category: 'Explainer',
    readingMinutes: 10,
    hero: '/blog/what-is-involuntary-churn-hero',
    heroAlt: 'A churn ring showing ~30% involuntary, with recoverable revenue rising as coins',
  },
  {
    slug: 'dunning-email-examples-templates',
    title: 'Dunning Email Examples: 12 Templates That Recover Failed Payments (2026)',
    description:
      '12 copy-paste dunning email templates that recover failed payments — a full sequence, templates by decline reason, subject lines, and the anatomy of one that converts.',
    excerpt:
      '12 copy-paste templates — a full recovery sequence, emails by decline reason, and special cases — plus the anatomy of a dunning email that converts and 15 subject lines.',
    date: '2026-07-08',
    author: 'Sinh Yang',
    category: 'Templates',
    readingMinutes: 16,
    hero: '/blog/dunning-email-examples-templates-hero',
    heroAlt: 'An envelope representing a recovery email with a green recovered checkmark',
  },
  {
    slug: 'stripe-decline-codes-explained',
    title: 'Stripe Decline Codes Explained: Every Code & How to Recover (2026)',
    description:
      'Every Stripe decline code explained — insufficient_funds, expired_card, do_not_honor and more — with soft vs hard classification, whether to retry, and how to recover each.',
    excerpt:
      'insufficient_funds, expired_card, do_not_honor and the rest — what each Stripe decline code means, whether it’s soft or hard, whether to retry, and how to recover it.',
    date: '2026-07-08',
    author: 'Sinh Yang',
    category: 'Reference',
    readingMinutes: 15,
    hero: '/blog/stripe-decline-codes-explained-hero',
    heroAlt: 'A declined card with three colour-coded Stripe decline code chips',
  },
  {
    slug: 'churnkey-alternatives',
    title: 'Churnkey Alternatives: 6 Cheaper Payment Recovery Tools (2026)',
    description:
      'The best Churnkey alternatives in 2026, compared — Revova, Churn Buster, Stunning, Baremetrics Recover and Paddle Retain — with pricing, a savings breakdown, and how to switch.',
    excerpt:
      'Churnkey starts around $199/mo. Here are the best cheaper alternatives — with a monthly-cost chart, a comparison table, annual savings, and a no-code guide to switching.',
    date: '2026-07-08',
    author: 'Sinh Yang',
    category: 'Comparison',
    readingMinutes: 12,
    hero: '/blog/churnkey-alternatives-hero',
    heroAlt: 'A crossed-out $199 Churnkey price tag replaced by a $29 alternative, 85% cheaper',
  },
  {
    slug: 'how-to-reduce-saas-churn',
    title: 'How to Reduce SaaS Churn: The Complete 2026 Guide',
    description:
      'A complete guide to reducing SaaS churn: split it into involuntary (failed payments) and voluntary, prioritize by impact vs effort, and follow a 30-day playbook with real levers.',
    excerpt:
      'Split churn into involuntary and voluntary, start with the quick wins, and follow a 30-day playbook — measuring, recovering failed payments, cancel flows, onboarding and more.',
    date: '2026-07-08',
    author: 'Sinh Yang',
    category: 'Guide',
    readingMinutes: 16,
    hero: '/blog/how-to-reduce-saas-churn-hero',
    heroAlt: 'A churn rate line trending downward with a green downward badge',
  },
]

// Newest first for listings.
export const sortedPosts = [...posts].sort((a, b) => (a.date < b.date ? 1 : -1))

export function getPost(slug: string): BlogPost | undefined {
  return posts.find((p) => p.slug === slug)
}
