// Blog post metadata — the single source of truth for the blog index, the
// per-post <head>, the sitemap, and JSON-LD. The article *bodies* live in
// components/blog/articles/* and are wired to slugs in app/blog/[slug]/page.tsx,
// so this file stays lightweight and importable from the sitemap.

export type BlogPost = {
  slug: string
  title: string
  description: string
  excerpt: string
  date: string // ISO date, publication
  updated?: string
  author: string
  category: string
  readingMinutes: number
  hero?: string // /public path WITHOUT extension; .avif + .webp are generated by scripts/gen-blog-images.mjs
  heroAlt?: string
}

export const posts: BlogPost[] = [
  {
    slug: 'best-payment-recovery-dunning-tools-2026',
    title: 'The 6 Best Payment Recovery (Dunning) Tools in 2026, Compared',
    description:
      'An honest comparison of the best failed-payment recovery tools in 2026 — Churnkey, Churn Buster, Stunning, Baremetrics Recover, Paddle Retain and Revova — with pricing, pros, cons, and how to choose.',
    excerpt:
      'Churnkey, Churn Buster, Stunning, Baremetrics Recover, Paddle Retain and Revova — what each is good at, roughly what it costs, and which one fits your stage and stack.',
    date: '2026-07-08',
    author: 'Revova',
    category: 'Comparison',
    readingMinutes: 15,
    hero: '/blog/best-payment-recovery-dunning-tools-2026-hero',
    heroAlt: 'Illustration of subscription revenue bars with failed payments being recovered back up',
  },
  {
    slug: 'how-to-recover-failed-stripe-payments',
    title: 'How to Recover Failed Stripe Payments: A 2026 Step-by-Step Guide',
    description:
      'Recover failed Stripe payments in 2026: smart retries, personalized dunning emails, pre-dunning, SCA handling and recovering past failures — a clear step-by-step guide.',
    excerpt:
      'Smart retries, personalized dunning emails, pre-dunning, SCA handling, and recovering the failures you’ve already lost — the full Stripe recovery stack, step by step.',
    date: '2026-07-08',
    author: 'Revova',
    category: 'Guide',
    readingMinutes: 11,
    hero: '/blog/how-to-recover-failed-stripe-payments-hero',
    heroAlt: 'A declined credit card recovered via a retry arc into a green checkmark',
  },
  {
    slug: 'what-is-involuntary-churn',
    title: 'What Is Involuntary Churn? (And How to Stop It) — 2026 Guide',
    description:
      'Involuntary churn is revenue lost to failed payments, not cancellations. Learn what it is, how it differs from voluntary churn, what it costs, and how to reduce it.',
    excerpt:
      'The churn caused by failed payments, not cancellations — what it is, how it differs from voluntary churn, why it compounds, and the proven stack to reduce it.',
    date: '2026-07-08',
    author: 'Revova',
    category: 'Explainer',
    readingMinutes: 10,
    hero: '/blog/what-is-involuntary-churn-hero',
    heroAlt: 'A churn ring showing ~30% involuntary, with recoverable revenue rising as coins',
  },
]

// Newest first for listings.
export const sortedPosts = [...posts].sort((a, b) => (a.date < b.date ? 1 : -1))

export function getPost(slug: string): BlogPost | undefined {
  return posts.find((p) => p.slug === slug)
}
